name: CI/CD for Heroku

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-python: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd $(dirname $(find . -name "manage.py" -not -path "*/.*" | head -n 1))
          python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      # Тут налаштовується деплой на Heroku за допомогою Heroku API Key (без фактичного розгортання)
      - name: Log execution
        run: echo "Ready to deploy to Heroku"

      - name: Run Tests
        working-directory: ./MIDDLE-TEST-2-MKR2-CI-CD
        run: |
          python manage.py test
